FROM rabbitmq:3.8

# IMPORTANT: When you update the version of the base image, 
# also update the rabbitmq.conf file to include any new settings
# included by the new base image.
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

