FROM jameslp/autograder-sandbox:3.1.0

RUN apt-get update --fix-missing && \
    apt-get install -y python3-wheel python3-setuptools default-jre python3-dev python3-pip

COPY requirements-485.txt .
RUN pip3 install --upgrade pip
RUN pip3 install -r requirements-485.txt
