FROM jameslp/autograder-sandbox:3.1.0

RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties

RUN add-apt-repository ppa:plt/racket
RUN add-apt-repository ppa:webupd8team/java
RUN add-apt-repository ppa:swi-prolog/stable
RUN add-apt-repository ppa:deadsnakes/ppa
RUN add-apt-repository ppa:ubuntu-toolchain-r/test

RUN apt-get update

RUN echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    apt-get install -y oracle-java8-installer
RUN apt-get install -y racket swi-prolog python3.6 gcc-7

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
