name: Publish Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for release'
        required: true
      set_as_latest:
        description: 'Set to the string "true" to also update the `latest` tag'
        required: false

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04

    permissions:
      contents: write  # IMPORTANT: mandatory for making GitHub Releases

    steps:
      - uses: actions/checkout@v3

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: >-
          gh release create
          "${{ inputs.version }}"
          --repo "$GITHUB_REPOSITORY"
          --notes ""
